USE XSGL
GO
--创建学生表
CREATE TABLE  STUDENT
(
SNO CHAR(9) PRIMARY KEY,
SNAME VARCHAR(20)NOT NULL,
SAGE INT,
SSEX CHAR(2) NOT NULL,
SDEPT VARCHAR(20)
)

--创建课程表
CREATE TABLE  COURSE
(
CNO CHAR(9) PRIMARY KEY,
CNAME VARCHAR(20) NOT NULL,
CREDIT INT NOT NULL
)

--学生成绩表
CREATE TABLE SC
(
SNO CHAR(9) NOT NULL,
CNO CHAR(9) NOT NULL,
GRADE INT
)

--添加主键
ALTER TABLE SC
ADD PRIMARY KEY(SNO,CNO)

--添加外键
ALTER TABLE SC
ADD CONSTRAINT FK_STUDENT_SC FOREIGN KEY(SNO)
REFERENCES STUDENT(SNO)
--经验   ------    sc是连接stu和cou的表，所以要这两个表的主要信息有了，才能向sc添加信息成功
ALTER TABLE SC
ADD CONSTRAINT FK_COURSE_SC FOREIGN KEY(CNO)
REFERENCES COURSE(CNO)

--插入信息
INSERT INTO STUDENT VALUES(17314141,'庄飞',21,'男','软件设计师')
INSERT INTO STUDENT VALUES(17314142,'庄妹',21,'女','软件设计师')
INSERT INTO COURSE VALUES('001','软考','2.0')

--查询表的信息
SELECT *FROM STUDENT
SELECT *FROM COURSE
SELECT *FROM SC

--插入信息
INSERT INTO SC VALUES('17314141','001',90)
INSERT INTO SC VALUES('17314142','001',99)

ALTER TABLE STUDENT
DROP CONSTRAINT DF_STUDENT_ssex

ALTER TABLE dbo.student ADD CONSTRAINT
 DF_STUDENT_SSEX DEFAULT '女' FOR SSEX

INSERT INTO STUDENT (SNO,SNAME,SAGE,SDEPT) VALUES('17314143','张三','28','产品经理')


